# Generated by Django 3.0.4 on 2020-03-19 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('deadline', models.DateField()),
                ('budget', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('OPEN', 'A request for a quote has been sent'), ('VALIDATING', 'A proposal/quote has been received'), ('APPROVED', 'A proposal/quote has been aproved and will be considered'), ('CHOSEN', 'The given projects actually chosen proposal'), ('CLOSED', 'The project proposal has been closed')], default='OPEN', max_length=100)),
                ('contractor', models.CharField(max_length=100)),
                ('contractor_email', models.CharField(max_length=100)),
                ('contractor_response', models.TextField()),
                ('offer', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='buildingmgmt.Project')),
            ],
            options={
                'ordering': [],
            },
        ),
    ]
