# Generated by Django 3.0.4 on 2020-03-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingmgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='contractor_response',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='offer',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='state',
            field=models.CharField(choices=[('OPEN', 'Open - A request for a quote has been sent'), ('VALIDATING', 'Validating - A proposal/quote has been received'), ('APPROVED', 'Approved - A proposal/quote has been aproved and will be considered'), ('CHOSEN', 'Chosen - The given projects actually chosen proposal'), ('CLOSED', 'Closed - The project proposal has been closed')], default='OPEN', max_length=100),
        ),
    ]
